### ISSUE TITLE
NPE in UnifiedSet intermal methods

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#1347]
Hi,

I'm not sure if it's a bug of `UnifiedSet` or my own code, but seeing the look of the stacktrace, I wonder if there are not an issue in how the internal state of the `UnifiedSet` is managed: I would have expected that if this value should not be null, it would have been detected earlier maybe?

This is the stacktrace, unfortunately I don't (yet) know how to reproduce it because it happened in the middle of complex processing :)
```
Caused by: java.lang.NullPointerException: null
	at org.eclipse.collections.impl.set.mutable.UnifiedSet.nonNullTableObjectEquals(UnifiedSet.java:2344)
	at org.eclipse.collections.impl.set.mutable.UnifiedSet.chainedAdd(UnifiedSet.java:270)
	at org.eclipse.collections.impl.set.mutable.UnifiedSet.add(UnifiedSet.java:257)
	at org.eclipse.collections.impl.set.mutable.UnifiedSet.rehash(UnifiedSet.java:381)
	at org.eclipse.collections.impl.set.AbstractUnifiedSet.rehash(AbstractUnifiedSet.java:135)
	at org.eclipse.collections.impl.set.mutable.UnifiedSet.add(UnifiedSet.java:251)
```

**Comment by mohrezaei** [comment]
These are almost always (client) multi-threading bugs. Is this map used in a multi-threaded context (and/or static, which is by nature multi-threaded)?

**Comment by victornoel** [comment]
@mohrezaei oh! you put your finger right on the issue :) thx!
