### ISSUE TITLE
Bug in UnifiedMap?

### ISSUE THREAD

**Issue by siddhsql** [eclipse/eclipse-collections#1524]
can someone tell me how is this screenshot possible:

<img width="727" alt="image" src="https://github.com/eclipse/eclipse-collections/assets/127623723/11bdbf93-fd72-47d3-a5d0-991d3cca75b1">

I can't give full code as this error is happening deep in my application but as you can see from the screenshot `nodes.get(t) == null)` evaluated to `true` and then when I immediately re-evaluated in the debugger it gives `false`.

**Comment by siddhsql** [comment]
changed from UnifiedMap to ConcurrentHashMap:

```
  ConcurrentHashMap<T, SimpleGraphVertex<T>> nodes = ConcurrentHashMap.newMap();
```

now getting:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at org.eclipse.collections.impl.set.mutable.UnifiedSet$PositionalIterator.next(UnifiedSet.java:1796)
	at essofore.hnswlib.AnotherSimpleGraph.outgoingEdgesOf(AnotherSimpleGraph.java:114)
	at essofore.hnswlib.HnswGraph.outgoingEdgesOf(HnswGraph.java:77)
	at essofore.hnswlib.HnswGraph.outgoingNeighborsOf(HnswGraph.java:48)
	at essofore.hnswlib.HnswIndex.searchLayer(HnswIndex.java:863)
	at essofore.hnswlib.HnswIndex.add_phase_two(HnswIndex.java:590)
	at essofore.hnswlib.HnswIndex.add(HnswIndex.java:356)
	at com.github.jelmerk.knn.Index.lambda$addAll$0(Index.java:142)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
```

if there is one thing all this tells is that multi-threading is REALLY HARD to get right

**Comment by motlin** [comment]
Your stack trace showed:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at org.eclipse.collections.impl.set.mutable.UnifiedSet$PositionalIterator.next(UnifiedSet.java:1796)
```

Which means you're mutating and reading non-thread-safe collections like UnifiedMap and UnifiedSet from multiple threads. This is a bug in your application, not in the framework, so I'll close this issue.
