### ISSUE TITLE
Code generation fails with NPE on Windows & OSX

### ISSUE THREAD

**Issue by willkil** [eclipse/eclipse-collections#164]
On OSX, I tried building at tags 7.1.0-javadoc-fix, 7.1.0, and on commit 8.0.0-26-gb40e3bb on master. On Windows I only tried commit 8.0.0-26-gb40e3bb.

Regardless I always get a variation of the output below, with the build failing on the "Eclipse Collections Main Library" step.

Searching for "antlr st4 internal error: java.lang.NullPointerException" yields [a similar issue] (https://github.com/ttsiodras/asn1scc/issues/10) whose root cause was a file naming conflict on case-insensitive file systems.

Here's the output:

```text
[INFO] --- eclipse-collections-code-generator-maven-plugin:7.1.0:generate (default) @ eclipse-collections ---
[DEBUG] Configuring mojo org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate from plugin realm ClassRealm[plugin>org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0, parent: sun.misc.Launcher$AppClassLoader@6d6f6e28]
[DEBUG] Configuring mojo 'org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate' with basic configurator -->
[DEBUG]   (f) project = MavenProject: org.eclipse.collections:eclipse-collections:7.1.0 @ /Users/will/targetstream/git/eclipse-collections/eclipse-collections/pom.xml
[DEBUG]   (f) templateDirectory = impl
[DEBUG] -- end configuration --
[INFO] Generating sources to eclipse-collections
[ERROR] String template run time error while processing [file:/Users/will/targetstream/git/eclipse-collections/eclipse-collections-code-generator/target/eclipse-collections-code-generator-7.1.0.jar!/impl/block/factory/primitivePredicates.stg]: context [/class /body] 29:5 internal error: java.lang.NullPointerException
	at org.stringtemplate.v4.STGroup.getEmbeddedInstanceOf(STGroup.java:177)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:235)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.stringtemplate.v4.ST.render(ST.java:491)
	at org.stringtemplate.v4.ST.render(ST.java:487)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.executeTemplate(EclipseCollectionsCodeGenerator.java:162)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.generateFiles(EclipseCollectionsCodeGenerator.java:112)
	at org.eclipse.collections.codegenerator.maven.GenerateMojo.execute(GenerateMojo.java:78)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[ERROR] String template run time error while processing [file:/Users/will/targetstream/git/eclipse-collections/eclipse-collections-code-generator/target/eclipse-collections-code-generator-7.1.0.jar!/impl/block/factory/primitivePredicates.stg]: context [/class] 1:0 internal error: java.lang.RuntimeException
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.logError(EclipseCollectionsCodeGenerator.java:228)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.runTimeError(EclipseCollectionsCodeGenerator.java:238)
	at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:152)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.stringtemplate.v4.ST.render(ST.java:491)
	at org.stringtemplate.v4.ST.render(ST.java:487)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.executeTemplate(EclipseCollectionsCodeGenerator.java:162)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.generateFiles(EclipseCollectionsCodeGenerator.java:112)
	at org.eclipse.collections.codegenerator.maven.GenerateMojo.execute(GenerateMojo.java:78)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse Collections Parent Project ................. SUCCESS [  0.609 s]
[INFO] Eclipse Collections Code Generator ................. SUCCESS [  3.070 s]
[INFO] Eclipse Collections Code Generator Ant Task ........ SUCCESS [  0.857 s]
[INFO] Eclipse Collections Code Generator Maven Plugin .... SUCCESS [  1.672 s]
[INFO] Eclipse Collections API ............................ SUCCESS [ 10.200 s]
[INFO] Eclipse Collections Main Library ................... FAILURE [  0.389 s]
[INFO] Eclipse Collections Test Utilities ................. SKIPPED
[INFO] Eclipse Collections Fork Join Utilities ............ SKIPPED
[INFO] Eclipse Collections Unit Test Suite ................ SKIPPED
[INFO] Eclipse Collections Scala Unit Test Suite .......... SKIPPED
[INFO] Eclipse Collections Serialization Test Suite ....... SKIPPED
[INFO] Eclipse Collections JMH Scala Test Suite ........... SKIPPED
[INFO] Eclipse Collections JMH Test Suite ................. SKIPPED
[INFO] Eclipse Collections Test Trait JUnit Runner ........ SKIPPED
[INFO] Eclipse Collections Java 8 Unit Test Suite ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.743 s
[INFO] Finished at: 2016-10-25T07:10:44-05:00
[INFO] Final Memory: 27M/517M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate (default) on project eclipse-collections: Execution default of goal org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate failed. RuntimeException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate (default) on project eclipse-collections: Execution default of goal org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.eclipse.collections:eclipse-collections-code-generator-maven-plugin:7.1.0:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.logError(EclipseCollectionsCodeGenerator.java:228)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.runTimeError(EclipseCollectionsCodeGenerator.java:238)
	at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:152)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.stringtemplate.v4.ST.render(ST.java:491)
	at org.stringtemplate.v4.ST.render(ST.java:487)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.executeTemplate(EclipseCollectionsCodeGenerator.java:162)
	at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.generateFiles(EclipseCollectionsCodeGenerator.java:112)
	at org.eclipse.collections.codegenerator.maven.GenerateMojo.execute(GenerateMojo.java:78)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
```

**Comment by itohro** [comment]
Thanks for reporting this. Could you please let us know what version of JDK/Maven are you building with? I build in Mac OSX (El Capitan) and cannot reproduce this.

As for the referenced issue, I see the NullPointerException is thrown in different place in the stack trace, so I suspect it is a different problem.

One another thing, could you please confirm if you made any changes to `eclipse-collections-code-generator/src/main/resources/impl/block/factory/primitivePredicates.stg`? The error suggests something went wrong while parsing this file.

**Comment by willkil** [comment]
Hi.

No, I had not modified anything because I was simply trying to create the source jars at the time.

Here's my OSX `mvn --version` output:
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T11:29:23-06:00)
Maven home: /opt/local/share/java/maven32
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

On Windows:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: C:\Program Files\Java\apache-maven-3.3.9
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_92\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

You could be correct that this issue is unrelated to file system case sensitivity, but you should double check that your FS is indeed case insensitive before ruling out this out. In particular, a networked FS may be case sensitive and OSX's hfs can be [configured case sensitive](http://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not).

**Comment by willkil** [comment]
Well this is interesting. The build succeeds in a ram disk on the same OSX machine, using the exact same JDK and maven, regardless of whether the ram disk is configured case sensitive or case insensitive. But the build still has the same failure when run on the main file system, even when I've freshly cloned the git repo. I also tried `mvn clean` and `rm -rf ~/.m2`, but each build behaves consistently.

**Comment by willkil** [comment]
I've confirmed this is caused by something on my local system. The build is fine outside some directories, but always fails in the same way in certain subdirectories.
