### ISSUE TITLE
Implement synchronized wrappers that use ReadWriteLock.

### ISSUE THREAD

**Issue by jankotek** [eclipse/eclipse-collections#196]
I had issue [opened in my project](https://github.com/jankotek/mapdb/pull/763). 

Current synchronized collections could be improved by using `ReadWriteLock` instead of `synchronized` keyword. This would improve concurrency; multiple parallel readers with single exclusive writer. 

I would be happy to provide a patch. Only change is to replace `synchronized` with:

```
lock.writeLock().lock()
try{
   //collection tasks
}finally{
  lock.writeLock.unlock()
}
```

There might be performance regression in some rare cases. JIT can optimize away synchronization if collection is used exclusively by single thread. But I think that is very rare case, if user explicitly asks for thread safe collection.

**Comment by motlin** [comment]
We have these synchronized wrappers, and we have MultiReader* collections like `MultiReaderFastList`. We don't have any wrappers that use ReadWriteLock AFAIK, but I think it's a good idea to add them. Note that it would have to be an addition, not a change to the synchronized wrappers, because it's a compatibility breaking change in behavior. Specifically, synchronizing on the wrapper itself would no longer work.

**Comment by jankotek** [comment]
Ok, I will send pull request
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/eclipse/e
> clipse-collections","title":"eclipse/eclipse-
> collections","subtitle":"GitHub repository","main_image_url":"https:/
> /cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-
> 11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/eclipse/eclipse-
> collections"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mo
> tlin in #196: We have these synchronized wrappers, and we have
> MultiReader* collections like `MultiReaderFastList`. We don't have
> any wrappers that use ReadWriteLock AFAIK, but I think it's a good
> idea to add them. Note that it would have to be an addition, not a
> change to the synchronized wrappers, because it's a compatibility
> breaking change in behavior. Specifically, synchronizing on the
> wrapper itself would no longer work."}],"action":{"name":"View
> Issue","url":"https://github.com/eclipse/eclipse-
> collections/issues/196#issuecomment-277716755"}}}

**Comment by donraab** [comment]
It looks based on the link above that you would like this on primitive collections, correct?

If you look at the MultiReader collections like MultiReaderFastList, you'll see we made the design decision to throw UnsupportedOperationException in iterator().  There are two methods that allow imperative code to be written safely with a read lock or write lock taken on the collection.  They are:

```
public void withReadLockAndDelegate(Procedure<MutableList<T>> procedure)
public void withWriteLockAndDelegate(Procedure<MutableList<T>> procedure)

```

I'm a big fan of symmetry, so it would be great to have this style of collection available on the primitive side as well, especially since you have a use case for them.  The question I would have is do you need a wrapper for the list, or can you take the same approach as we did with the MultiReader collections on the object side?

**Comment by jankotek** [comment]
ok, will have a look at that. 

I understand problem with iterators.

**Comment by jankotek** [comment]
Please reopen this issue, I am working on a pull request.

**Comment by motlin** [comment]
Renamed the title to more accurately reflect the work, and reopening.

**Comment by jankotek** [comment]
@motlin @donraab 
I implemented MultiReaderPrimitiveList. I want with wrapper, rather than separate implementation, because it has way less code duplication. Separate implementation would not offer any bonuses over wrapper, `foreach` works similar way on both.

I have a patch ready:
https://github.com/jankotek/eclipse-collections/commit/5e324423ad27414d832e205b84bf4b3600ea8e21

It passes unit tests, but code generator fails with with exception bellow. I am not sure howto hook new STG templates and files into build script. I tried to read doc, search names etc... But at this point I need your help.

MultiReader STG template is  based on synchronized wrapper. Code generation only fails if I changed target file name from:
```
fileName(primitive) ::= "Synchronized<primitive.name>ListTest"
```
To:
```
fileName(primitive) ::= "MultiReader<primitive.name>ListTest"
```
Maven exception:

```
  
[INFO] --- eclipse-collections-code-generator-maven-plugin:8.1.0-RC:generate (list) @ unit-tests ---
[INFO] Generating sources to unit-tests
[ERROR] String template run time error while processing [/home/jan/os/eclipse-collections/eclipse-collections-code-generator/target/classes/test/list/mutable/multiReaderPrimitiveListTest.stg]: context [/class /body] 18:86 no such template: /no matching literal
[ERROR] String template run time error while processing [/home/jan/os/eclipse-collections/eclipse-collections-code-generator/target/classes/test/list/mutable/multiReaderPrimitiveListTest.stg]: context [/class /body] 18:86 internal error: java.lang.RuntimeException
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.logError(EclipseCollectionsCodeGenerator.java:228)
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.runTimeError(EclipseCollectionsCodeGenerator.java:240)
        at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
        at org.stringtemplate.v4.STGroup.getEmbeddedInstanceOf(STGroup.java:183)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:235)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.ST.write(ST.java:427)
        at org.stringtemplate.v4.ST.render(ST.java:497)
        at org.stringtemplate.v4.ST.render(ST.java:491)
        at org.stringtemplate.v4.ST.render(ST.java:487)
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.executeTemplate(EclipseCollectionsCodeGenerator.java:162)
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.generateFiles(EclipseCollectionsCodeGenerator.java:112)
        at org.eclipse.collections.codegenerator.maven.GenerateMojo.execute(GenerateMojo.java:79)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[ERROR] String template run time error while processing [/home/jan/os/eclipse-collections/eclipse-collections-code-generator/target/classes/test/list/mutable/multiReaderPrimitiveListTest.stg]: context [/class] 1:0 internal error: java.lang.RuntimeException
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.logError(EclipseCollectionsCodeGenerator.java:228)
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator$LoggingErrorListener.runTimeError(EclipseCollectionsCodeGenerator.java:240)
        at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:152)
        at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
        at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
        at org.stringtemplate.v4.ST.write(ST.java:427)
        at org.stringtemplate.v4.ST.render(ST.java:497)
        at org.stringtemplate.v4.ST.render(ST.java:491)
        at org.stringtemplate.v4.ST.render(ST.java:487)
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.executeTemplate(EclipseCollectionsCodeGenerator.java:162)
        at org.eclipse.collections.codegenerator.EclipseCollectionsCodeGenerator.generateFiles(EclipseCollectionsCodeGenerator.java:112)
        at org.eclipse.collections.codegenerator.maven.GenerateMojo.execute(GenerateMojo.java:79)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Eclipse Collections Parent Project ................. SUCCESS [  0.317 s]
[INFO] Eclipse Collections Code Generator ................. SUCCESS [  1.471 s]
[INFO] Eclipse Collections Code Generator Ant Task ........ SUCCESS [  0.579 s]
[INFO] Eclipse Collections Code Generator Maven Plugin .... SUCCESS [  1.300 s]
[INFO] Eclipse Collections API ............................ SUCCESS [  6.791 s]
[INFO] Eclipse Collections Main Library ................... SUCCESS [ 38.458 s]
[INFO] Eclipse Collections Test Utilities ................. SUCCESS [  7.192 s]
[INFO] Eclipse Collections Fork Join Utilities ............ SUCCESS [  5.691 s]
[INFO] Eclipse Collections Unit Test Suite ................ FAILURE [  1.173 s]
[INFO] Eclipse Collections Scala Unit Test Suite .......... SKIPPED
[INFO] Eclipse Collections Serialization Test Suite ....... SKIPPED
[INFO] Eclipse Collections JMH Scala Test Suite ........... SKIPPED
[INFO] Eclipse Collections JMH Test Suite ................. SKIPPED
[INFO] Eclipse Collections Test Trait JUnit Runner ........ SKIPPED
[INFO] Eclipse Collections Java 8 Unit Test Suite ......... SKIPPED
[INFO] Eclipse Collections Test Coverage Aggregation ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by nikhilnanivadekar** [comment]
@jankotek Apologies, I could not get to this earlier. I have pushed a fix to my fork.
[nikhilnanivadekar@486c658](https://github.com/nikhilnanivadekar/eclipse-collections/commit/486c6582ec054fbb584a779286b68d505dca9c3b).

The issue was _not_ with you template files. We do not have `[literal](https://github.com/eclipse/eclipse-collections/blob/0db19cf63e53dafeb59ac46b582fa0a266c600c5/eclipse-collections-code-generator/src/main/resources/primitiveLiteral.stg)`s for `boolean`, so you need to write the test class for `MultiReaderBooleanList` by hand. Once that class is found, the build will not try to code generate it. The exception was mentioning that.

**Comment by jankotek** [comment]
I added pull request for Primitive Lists, other collections will follow
https://github.com/eclipse/eclipse-collections/pull/262

**Comment by donraab** [comment]
@jankotek @nikhilnanivadekar Should this issue be closed, as I see the PR mentioned #262 was closed ?

**Comment by jankotek** [comment]
I dont have a time to work on this, sorry.

**Comment by donraab** [comment]
No worries. Thank you.
