### ISSUE TITLE
Build on Android fails with ArrayIndexOutOfBoundsException: 65535

### ISSUE THREAD

**Issue by saudet** [eclipse/eclipse-collections#510]
We would like to use the Eclipse Collections as part of Eclipse Deeplearning4j, but we found it to be incompatible with Android for unclear reasons, see https://github.com/deeplearning4j/deeplearning4j/issues/5087. Basically, whenever `org.eclipse.collections:eclipse-collections` is added as a dependency, to an otherwise empty project create with Android Studio, for example, the build ends with the following kind of stack trace. I've tested versions 8.2.0, 9.1.0, and 9.2.0.M1 of `org.eclipse.collections:eclipse-collections`, as well as versions 3.0.1, 3.1.0, and 3.1.2 of `com.android.tools.build:gradle` with Android Studio 3.1.2, all with similar outcomes.

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.ArrayIndexOutOfBoundsException
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
Caused by: com.android.build.api.transform.TransformException: java.lang.ArrayIndexOutOfBoundsException
	at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:225)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 48 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:397)
	at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:221)
	... 51 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535
	at com.android.tools.r8.graph.OffsetToObjectMapping.getMethod(OffsetToObjectMapping.java:104)
	at com.android.tools.r8.dex.DexFileReader.methodHandleAt(DexFileReader.java:960)
	at com.android.tools.r8.dex.DexFileReader.populateMethodHandles(DexFileReader.java:853)
	at com.android.tools.r8.dex.DexFileReader.populateIndexTables(DexFileReader.java:838)
	at com.android.tools.r8.dex.ApplicationReader$ClassReader.readDexSources(ApplicationReader.java:206)
	at com.android.tools.r8.dex.ApplicationReader$ClassReader.readSources(ApplicationReader.java:253)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:114)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
	at com.android.tools.r8.D8.run(D8.java:156)
	at com.android.tools.r8.D8.lambda$run$0(D8.java:71)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

If you believe the Android team should be looking into that, feel free to close this issue, but my guess is this will never get fixed by them since no other libraries appear to be triggering that exception...

/cc @AlexDBlack

**Comment by saudet** [comment]
Thanks for follow up! Multidex doesn't solve this though. It's supposed to be enabled by default these days, and I've just tried adding `multiDexEnabled true` just to make sure, but nothing changes, so it's something else.

Right, ProGuard could work for release builds, but this doesn't solve issues during development, for debug builds.

Would you have a list of suspicious classes that might be causing this and that we could try to exclude manually in the build file?

**Comment by nikhilnanivadekar** [comment]
Try to exclude primitive collections especially all PrimitivePrimitiveMaps, PrimitiveObjectMaps and ObjectPrimitiveMap except ObjectIntMap. Please keep the ones which you plan to use. ObjectIntMap is used by our Bag implementation. But that might be cumbersome in my opinion. I have not excluded specific classes in the build, so I don't know if you can wildcard the exclusions.

To help Android and IoT developers it has been a long standing Wish list item to break the library further in to modules for primitive collections. But we are yet to start development for that.

**Comment by nikhilnanivadekar** [comment]
Please reopen the issue if you have any further questions.

**Comment by saudet** [comment]
Well, it would be nice to know exactly which classes to skip, including a complete list of classes that depend on them, and consequently which features are unavailable on Android. If there is a feature that we would really like to use tough, we will most likely start debugging this by ourselves, but probably not before.

**Comment by AlexDBlack** [comment]
Thanks for the replies. Figured I'll chime in here as well.

Excluding specific classes may be a workaround, but it's not an approach that we (or at least I) would be supportive of using. I suspect this approach would be challenging to maintain, especially given our android testing infrastructure isn't nearly as thorough as on PC.

Is there any rough timeline for the refactoring/additional modules?

**Comment by nikhilnanivadekar** [comment]
It is on our To Do list, however, no solid timelines yet.
I will gladly take any help/contribution I could get for this feature. Would you or anyone from your team like to contribute?

**Comment by AlexDBlack** [comment]
Thanks. As much as I'd love for this to be fixed (I do like Eclipse Collections quite a lot :)), unfortunately I don't think this would be something we could allocate engineering time to in the near future.

**Comment by motlin** [comment]
@saudet ProGaurd prunes out classes that you don't use in your project, so there's no general list that will work for everybody. However, we know that pruning out all primitive collections reduces the code size by well over half, and many folks don't use the primitive collections.

**Comment by saudet** [comment]
One more thing, recent versions of the Collections appear to rely on Java 8, but Android still has very limited support for Java 8...

@motlin ProGuard works well for release builds, but isn't really practical for debug builds. Users of Deeplearning4j are typically developers, not end users.
