### ISSUE TITLE
Java 10, Java 11-EA builds failing due to EBR plugin

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#535]
The Java 10 and Java 11-EA builds are failing due to API compatibility issue in the EBR plugin while creating OSGi artifacts.

Example log: https://api.travis-ci.org/v3/job/394162025/log.txt

```
21:19:47:456 [ERROR] Failed to execute goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle (default-bundle) on project org.eclipse.collections: Execution default-bundle of goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle failed: An API incompatibility was encountered while executing org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle: java.lang.ExceptionInInitializerError: null
21:19:47:456 [ERROR] -----------------------------------------------------
21:19:47:457 [ERROR] realm =    extension>org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT
```

@guw @ujhelyiz Can either of you please help?

**Comment by ujhelyiz** [comment]
I am sorry, but I cannot be of real help, as I am not familiar with building on Java 10 neither the error message you have encountered. With a quick search, I have seen that this error usually means some kind of classpath error, but I don't know what. However, what I would try are the following:

 * I have looked at the classpath from the log, and have seen entries for Apache commons-lang 3.7 and Apache commons-lang 2.1. I don't know whether they are safe to have on the same classpath or not, but that might be worth looking into.
 * I'd run the build with -X (or at least -e), because at the end we would get some information about where we were during the execution of the plugin, making it easier to guess what did not resolve correctly.

**Comment by guw** [comment]
@nikhilnanivadekar Can you run with stack trace enabled so that we can spot the error?

**Comment by nikhilnanivadekar** [comment]
@guw @ujhelyiz I ran the build with -e, cannot run in debug (-X) as the logs exceed Travis limit. Here is the link to log: https://api.travis-ci.org/v3/job/395048845/log.txt

```
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:181)
	... 21 more
Caused by: java.lang.ExceptionInInitializerError
	at org.eclipse.ebr.maven.BundleMojo.assembleJar(BundleMojo.java:259)
	at org.eclipse.ebr.maven.BundleMojo.createPluginJar(BundleMojo.java:430)
	at org.eclipse.ebr.maven.BundleMojo.buildBundle(BundleMojo.java:365)
	at org.eclipse.ebr.maven.BundleMojo.execute(BundleMojo.java:462)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.<clinit>(AbstractZipArchiver.java:118)
	... 26 more
```

I will run the build in debug mode in my local machine later today, but wanted to give this info, in case it helps isolate the issue. Looking at the ArrayIndexOutOfBounds, I wonder is the ebr plugin compatible for Java 10, Java 11? I recon it might be because the version numbers have become double digit?

**Comment by ujhelyiz** [comment]
This trace looks helpful, it is really similar to a lot of issues around, and basically is related to an old version of plexus-archiver used. Tycho updated to plexus-archiver 3.4 to solve this issue, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=514119 for details. Given this build uses 2.8.1 for this component, I'd guess this will be the main culprit of the issue.

**Comment by nikhilnanivadekar** [comment]
@ujhelyiz may be you can contribute the fix 😄 ?

**Comment by guw** [comment]
@nikhilnanivadekar I'm surprised you got that far. I ran into quite a few issues building EBR on JDK 10.

Feel free to follow progress here: https://github.com/eclipse/ebr/commits/gunnar/jdk

**Comment by nikhilnanivadekar** [comment]
@guw For the sake of contributors (there are 3 PRs stuck because of build failures), should I accept the build failures as long as they are related to OSGi, and we will eventually fix it?
Thoughts?

**Comment by guw** [comment]
@ujhelyiz Can you explain what `p2-feature` folder is about? I think this is new?

**Comment by ujhelyiz** [comment]
@nikhilnanivadekar I could have a look, but not until the weekend.

@guw The p2-feature project contains a separate, Tycho-based build that creates an eclipse feature and a corresponding p2 repository (that includes the bundle created in an earlier run in the p2-repository folder).

**Comment by nikhilnanivadekar** [comment]
The build still seems to fail: https://api.travis-ci.org/v3/job/395608107/log.txt

Re-opening the issue.

**Comment by nikhilnanivadekar** [comment]
The build has gone through fine. I will keep this issue open in case the build behaves erratically in the next week, will close if works fine. Thanks!

**Comment by guw** [comment]
@nikhilnanivadekar Do you cache Maven repos between builds?

**Comment by nikhilnanivadekar** [comment]
It shouldn't because each build starts with a new maven download. But that could possibly be the reason.

**Comment by nikhilnanivadekar** [comment]
Tested that the builds are going through consistently. Closing the issue!
Thanks for your help!
