### ISSUE TITLE
LongLongHashMap throws OOM

### ISSUE THREAD

**Issue by superhx** [eclipse/eclipse-collections#576]
Test Code:

``` java
MutableLongLongMap map = new LongLongHashMap();
long putLong = 0;
for (; putLong < 1000; putLong++) {
    map.put(putLong, putLong);
}
for (; putLong < (1 << 30); putLong++) {
    map.put(putLong, putLong);
    map.remove(putLong - 1000);
}
```

OOM Stack:
``` java
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.allocateTable(LongLongHashMap.java:1248)
	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.rehash(LongLongHashMap.java:1136)
	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.rehashAndGrow(LongLongHashMap.java:1129)
	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.addKeyValueAtIndex(LongLongHashMap.java:704)
	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.put(LongLongHashMap.java:364)
	at xyz.robinhan.boxing.Main.main(Main.java:24)
```

**Comment by nikhilnanivadekar** [comment]
Closed via #552 
The fix will be available in the 10.0 milestone version to be released next Friday.
