### ISSUE TITLE
org.eclipse.collections.impl.map.mutable.primitive.ObjectLongHashMap.getIfAbsentPut is throwing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by etsrepo** [eclipse/eclipse-collections#622]
Java 1.8
Spring Boot

`java.lang.ArrayIndexOutOfBoundsException: 30274
        at org.eclipse.collections.impl.map.mutable.primitive.ObjectLongHashMap.addKeyValueAtIndex(ObjectLongHashMap.java:535)
        at org.eclipse.collections.impl.map.mutable.primitive.ObjectLongHashMap.getIfAbsentPut(ObjectLongHashMap.java:471)`

**Comment by nikhilnanivadekar** [comment]
This was fixed already in #491 and #492 and released as a part of [9.2.0](https://github.com/eclipse/eclipse-collections/releases/tag/9.2.0) release
The fix was back-ported to service releases. 
Please reopen this request if you face the issue for any of the service releases or for 9.2.0. Also, provide a failing test case. 
Thanks!
