### ISSUE TITLE
EBR Plugin failures for local, Travis and Teamcity builds

### ISSUE THREAD

**Issue by cguntur-bnym** [eclipse/eclipse-collections#704]
Builds are consistently failing in the Eclipse Collections OSGi Bundle module with the exception:

[21:26:29][Step 1/1] Failed to execute goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle (default-bundle) on project org.eclipse.collections: Unable to execute mojo

More detailed error message can be located at the build log: https://teamcity.jetbrains.com/viewLog.html?buildId=2060159&buildTypeId=OpenSourceProjects_EclipseCollections_CheckStyle&tab=buildLog&_focus=2998 (also attached to this issue)

[Eclipse_Collections_CheckStyle_1135.log.zip](https://github.com/eclipse/eclipse-collections/files/2974169/Eclipse_Collections_CheckStyle_1135.log.zip

I noticed this issue from earlier and am tagging the same parties with the hope that they know what resolved the issue the previous time. Link to prior closed issue: https://github.com/eclipse/eclipse-collections/issues/535

@guw @ujhelyiz @nikhilnanivadekar @donraab

**Comment by guw** [comment]
Happy to help! Please post the complete error message. There should be additional error messages than just "Unable to execute mojo". You can also run Maven with "-e" to print full stack traces.

**Comment by cguntur-bnym** [comment]
Thank you Gunnar. Please find the stack trace from the builds (I also included the complete build log in the original issue, in case you wanted to see further details.

Stack trace:
`
[21:26:30][Step 1/1] [ERROR] Failed to execute goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle (default-bundle) on project org.eclipse.collections: Unable to execute mojo: Execution null of goal org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT:assemble-bundle-p2-repository failed: An API incompatibility was encountered while executing org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT:assemble-bundle-p2-repository: java.lang.NoSuchMethodError: org.eclipse.tycho.p2.tools.DestinationRepositoryDescriptor.<init>(Ljava/io/File;Ljava/lang/String;ZZZZZLjava/util/Map;)V
[21:26:30][Step 1/1] [ERROR] -----------------------------------------------------
[21:26:30][Step 1/1] [ERROR] realm =    plugin>org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT
[21:26:30][Step 1/1] [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[21:26:30][Step 1/1] [ERROR] urls[0] = file:/home/teamcity/.m2/repository/org/eclipse/ebr/ebr-tycho-extras-plugin/1.0.0-SNAPSHOT/ebr-tycho-extras-plugin-1.0.0-SNAPSHOT.jar
[21:26:30][Step 1/1] [ERROR] urls[1] = file:/home/teamcity/.m2/repository/org/eclipse/ebr/ebr-maven-shared/1.0.0-SNAPSHOT/ebr-maven-shared-1.0.0-SNAPSHOT.jar
[21:26:30][Step 1/1] [ERROR] urls[2] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[21:26:30][Step 1/1] [ERROR] urls[3] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-text/1.6/commons-text-1.6.jar
[21:26:30][Step 1/1] [ERROR] urls[4] = file:/home/teamcity/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
[21:26:30][Step 1/1] [ERROR] urls[5] = file:/home/teamcity/.m2/repository/org/eclipse/tycho/tycho-p2-repository-plugin/1.3.0/tycho-p2-repository-plugin-1.3.0.jar
[21:26:30][Step 1/1] [ERROR] urls[6] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[21:26:30][Step 1/1] [ERROR] urls[7] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[21:26:30][Step 1/1] [ERROR] urls[8] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-archiver/3.4/plexus-archiver-3.4.jar
[21:26:30][Step 1/1] [ERROR] urls[9] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-io/2.7.1/plexus-io-2.7.1.jar
[21:26:30][Step 1/1] [ERROR] urls[10] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-compress/1.11/commons-compress-1.11.jar
[21:26:30][Step 1/1] [ERROR] urls[11] = file:/home/teamcity/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[21:26:30][Step 1/1] [ERROR] urls[12] = file:/home/teamcity/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar
[21:26:30][Step 1/1] [ERROR] urls[13] = file:/home/teamcity/.m2/repository/org/eclipse/tycho/org.eclipse.osgi.compatibility.state/1.1.100.v20180131-1413/org.eclipse.osgi.compatibility.state-1.1.100.v20180131-1413.jar
[21:26:30][Step 1/1] [ERROR] Number of foreign imports: 1
[21:26:30][Step 1/1] [ERROR] import: Entry[import  from realm ClassRealm[project>org.eclipse.collections:p2-repository:10.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[21:26:30][Step 1/1] [ERROR] 
[21:26:30][Step 1/1] [ERROR] -----------------------------------------------------
[21:26:30][Step 1/1] [ERROR] -> [Help 1]
[21:26:30][Step 1/1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle (default-bundle) on project org.eclipse.collections: Unable to execute mojo
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[21:26:30][Step 1/1] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[21:26:30][Step 1/1] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[21:26:30][Step 1/1] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[21:26:30][Step 1/1] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[21:26:30][Step 1/1] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[21:26:30][Step 1/1] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[21:26:30][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:26:30][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:26:30][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:26:30][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:26:30][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[21:26:30][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[21:26:30][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[21:26:30][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[21:26:30][Step 1/1] Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
[21:26:30][Step 1/1] 	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:128)
[21:26:30][Step 1/1] 	at org.eclipse.ebr.maven.BundleMojo.assembleP2Repository(BundleMojo.java:293)
[21:26:30][Step 1/1] 	at org.eclipse.ebr.maven.BundleMojo.execute(BundleMojo.java:466)
[21:26:30][Step 1/1] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[21:26:30][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[21:26:30][Step 1/1] 	... 20 more
[21:26:30][Step 1/1] Caused by: org.apache.maven.plugin.PluginExecutionException: Execution null of goal org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT:assemble-bundle-p2-repository failed: An API incompatibility was encountered while executing org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT:assemble-bundle-p2-repository: java.lang.NoSuchMethodError: org.eclipse.tycho.p2.tools.DestinationRepositoryDescriptor.<init>(Ljava/io/File;Ljava/lang/String;ZZZZZLjava/util/Map;)V
[21:26:30][Step 1/1] -----------------------------------------------------
[21:26:30][Step 1/1] realm =    plugin>org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT
[21:26:30][Step 1/1] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[21:26:30][Step 1/1] urls[0] = file:/home/teamcity/.m2/repository/org/eclipse/ebr/ebr-tycho-extras-plugin/1.0.0-SNAPSHOT/ebr-tycho-extras-plugin-1.0.0-SNAPSHOT.jar
[21:26:30][Step 1/1] urls[1] = file:/home/teamcity/.m2/repository/org/eclipse/ebr/ebr-maven-shared/1.0.0-SNAPSHOT/ebr-maven-shared-1.0.0-SNAPSHOT.jar
[21:26:30][Step 1/1] urls[2] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[21:26:30][Step 1/1] urls[3] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-text/1.6/commons-text-1.6.jar
[21:26:30][Step 1/1] urls[4] = file:/home/teamcity/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
[21:26:30][Step 1/1] urls[5] = file:/home/teamcity/.m2/repository/org/eclipse/tycho/tycho-p2-repository-plugin/1.3.0/tycho-p2-repository-plugin-1.3.0.jar
[21:26:30][Step 1/1] urls[6] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[21:26:30][Step 1/1] urls[7] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[21:26:30][Step 1/1] urls[8] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-archiver/3.4/plexus-archiver-3.4.jar
[21:26:30][Step 1/1] urls[9] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-io/2.7.1/plexus-io-2.7.1.jar
[21:26:30][Step 1/1] urls[10] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-compress/1.11/commons-compress-1.11.jar
[21:26:30][Step 1/1] urls[11] = file:/home/teamcity/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[21:26:30][Step 1/1] urls[12] = file:/home/teamcity/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar
[21:26:30][Step 1/1] urls[13] = file:/home/teamcity/.m2/repository/org/eclipse/tycho/org.eclipse.osgi.compatibility.state/1.1.100.v20180131-1413/org.eclipse.osgi.compatibility.state-1.1.100.v20180131-1413.jar
[21:26:30][Step 1/1] Number of foreign imports: 1
[21:26:30][Step 1/1] import: Entry[import  from realm ClassRealm[project>org.eclipse.collections:p2-repository:10.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[21:26:30][Step 1/1] 
[21:26:30][Step 1/1] -----------------------------------------------------
[21:26:30][Step 1/1] 
[21:26:30][Step 1/1] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:183)
[21:26:30][Step 1/1] 	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:119)
[21:26:30][Step 1/1] 	... 24 more
[21:26:30][Step 1/1] Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT:assemble-bundle-p2-repository: java.lang.NoSuchMethodError: org.eclipse.tycho.p2.tools.DestinationRepositoryDescriptor.<init>(Ljava/io/File;Ljava/lang/String;ZZZZZLjava/util/Map;)V
[21:26:30][Step 1/1] -----------------------------------------------------
[21:26:30][Step 1/1] realm =    plugin>org.eclipse.ebr:ebr-tycho-extras-plugin:1.0.0-SNAPSHOT
[21:26:30][Step 1/1] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[21:26:30][Step 1/1] urls[0] = file:/home/teamcity/.m2/repository/org/eclipse/ebr/ebr-tycho-extras-plugin/1.0.0-SNAPSHOT/ebr-tycho-extras-plugin-1.0.0-SNAPSHOT.jar
[21:26:30][Step 1/1] urls[1] = file:/home/teamcity/.m2/repository/org/eclipse/ebr/ebr-maven-shared/1.0.0-SNAPSHOT/ebr-maven-shared-1.0.0-SNAPSHOT.jar
[21:26:30][Step 1/1] urls[2] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[21:26:30][Step 1/1] urls[3] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-text/1.6/commons-text-1.6.jar
[21:26:30][Step 1/1] urls[4] = file:/home/teamcity/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
[21:26:30][Step 1/1] urls[5] = file:/home/teamcity/.m2/repository/org/eclipse/tycho/tycho-p2-repository-plugin/1.3.0/tycho-p2-repository-plugin-1.3.0.jar
[21:26:30][Step 1/1] urls[6] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[21:26:30][Step 1/1] urls[7] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[21:26:30][Step 1/1] urls[8] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-archiver/3.4/plexus-archiver-3.4.jar
[21:26:30][Step 1/1] urls[9] = file:/home/teamcity/.m2/repository/org/codehaus/plexus/plexus-io/2.7.1/plexus-io-2.7.1.jar
[21:26:30][Step 1/1] urls[10] = file:/home/teamcity/.m2/repository/org/apache/commons/commons-compress/1.11/commons-compress-1.11.jar
[21:26:30][Step 1/1] urls[11] = file:/home/teamcity/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[21:26:30][Step 1/1] urls[12] = file:/home/teamcity/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar
[21:26:30][Step 1/1] urls[13] = file:/home/teamcity/.m2/repository/org/eclipse/tycho/org.eclipse.osgi.compatibility.state/1.1.100.v20180131-1413/org.eclipse.osgi.compatibility.state-1.1.100.v20180131-1413.jar
[21:26:30][Step 1/1] Number of foreign imports: 1
[21:26:30][Step 1/1] import: Entry[import  from realm ClassRealm[project>org.eclipse.collections:p2-repository:10.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[21:26:30][Step 1/1] 
[21:26:30][Step 1/1] -----------------------------------------------------
[21:26:30][Step 1/1] 
[21:26:30][Step 1/1] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:181)
[21:26:30][Step 1/1] 	... 25 more
[21:26:30][Step 1/1] Caused by: java.lang.NoSuchMethodError: org.eclipse.tycho.p2.tools.DestinationRepositoryDescriptor.<init>(Ljava/io/File;Ljava/lang/String;ZZZZZLjava/util/Map;)V
[21:26:30][Step 1/1] 	at org.eclipse.ebr.tycho.extras.plugin.AssembleBundleP2RepositoryMojo.execute(AssembleBundleP2RepositoryMojo.java:172)
[21:26:30][Step 1/1] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[21:26:30][Step 1/1] 	... 25 more
[21:26:30][Step 1/1] [ERROR] 
[21:26:30][Step 1/1] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[21:26:30][Step 1/1] [ERROR] 
[21:26:30][Step 1/1] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[21:26:30][Step 1/1] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[21:26:30][Step 1/1] [ERROR] 
[21:26:30][Step 1/1] [ERROR] After correcting the problems, you can resume the build with the command
[21:26:30][Step 1/1] [ERROR]   mvn <goals> -rf :org.eclipse.collections
[21:26:31][Step 1/1] Process exited with code 1
`

**Comment by guw** [comment]
Can you set the Tycho version to `1.3.0` please?
https://github.com/eclipse/eclipse-collections/blob/master/p2-repository/pom.xml#L52-L53

I also suggest to get rid of `tycho-extras-version` property and always use just `tycho-version`. They are synchronized and there shouldn't be a need to have them diverge.

**Comment by cguntur-bnym** [comment]
Pom modified with both suggestions, running a local build, once verified will proceed to push. Will update here on progress. Thanks Gunnar !

**Comment by cguntur-bnym** [comment]
Build succeeded locally. Travis builds triggered after push.
